### PR TITLE
 Handle unsized dyn trait objects as source of casts

### LINKED ISSUE #203: Standard library function `<(dyn core::any::Any + core::marker::Send + 'static)>::downcast_ref` does not codegen
```
            // thread 'rustc' panicked at 'Can't cast
            // Expr { value: Symbol { identifier: "_ZN54_$LT$dyn$u20$core..any..Any$u2b$core..marker..Send$GT$12downcast_ref17hfd95d38a01cb23d4E::1::var_3" }, typ: StructTag("tag-dyn core::any::Any + core::marker::Send"), location: None }
            // Pointer { typ: Empty }', compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/expr.rs:408:9
```

related: #109

### PR DESCRIPTION
**Pull request by avanhatt**
### Description of changes: 

We previously assumed that any `PointerCast::Unsize` is from a sized pointer to either a sized or unsized pointer. However, when auto traits (like `Send`) are in play, pointer casts can be _from_ an unsized pointer as well. This is because auto traits have no associated functions, so the underlying vtable does not need to change in a cast from some dynamic trait object reference with an auto trait to another without that trait. For example, this is legal:
```rust
&(dyn Any + Send) -> &dyn Any
```

This change adds a new cast case that essentially copies the source fat pointer to a destination fat pointer where the vtable is casted to the new type.

### Resolved issues:

Resolves #203. 

### Call-outs:

I have a TODO to see if we can actually assert that the difference between the source and destination of the cast differ only by auto traits, I suspect core Rust has a utility for this somewhere.

### Testing:

* How is this change tested?
Existing regression tests, 2 new tests that previously panicked RMC and now passes (pass and fail versions).

* Is this a refactor change?
No. 

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs [hunk 1]
```diff
@@ -656,11 +656,25 @@ impl<'tcx> GotocCtx<'tcx> {
...
                 let dst_mir_type = t;
-                let dst_goto_expr = self.cast_sized_expr_to_unsized_expr(
-                    src_goto_expr.clone(),
-                    src_mir_type,
-                    dst_mir_type,
-                );
+
+                // Check if the cast is from a vtable fat pointer to another
+                // unsized type (which can happen with auto trait fat pointers)
+                let possible_dyn_src = dyn_from_vtable_fat_pointer(src_mir_type);
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:662]: do you use this? If not, maybe just move it to the next line

File: src/test/cbmc/DynTrait/any_cast_int_fail.rs [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+// is an auto trait with no associated function (so the underlying vtable is 
+// the same before and after the cast).
+
+// We can also downcast Any to a backing concrete type.
+// Inverted assert for _fail test.
+
+fn downcast_to_concrete(a: &dyn Any) {
+    match a.downcast_ref::<i32>() {
+        Some(i) => {
+            assert!(*i == 8);
```
[the remark this answers is not in the document]
Comment (avanhatt) [reply src/test/cbmc/DynTrait/any_cast_int_fail.rs:16]: Doesn't work off main because of the fix needed in my other open PR

File: compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs (hunk 1 above)
Comment (avanhatt) [reply compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs]: Done!

File: src/test/cbmc/DynTrait/any_cast_int_fail.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (avanhatt) [reply src/test/cbmc/DynTrait/any_cast_int_fail.rs]: Rebased from new main and done

File: compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs [hunk 3]
```diff
@@ -845,6 +859,48 @@ impl<'tcx> GotocCtx<'tcx> {
...
+    /// functions, the underlying vtable does not need to change.
+    ///
+    /// Cast a pointer from one usized dynamic trait object to another. The
+    /// result  of the cast will be a fat pointer with the same data and
+    /// vtable, but the new type. Returns None if no cast is needed.
+    fn cast_unsized_dynamic_to_unsized_dynamic(
+        &mut self,
+        src_goto_expr: Expr,
+        src_mir_type: Ty<'tcx>,
+        src_mir_dyn_ty: Ty<'tcx>,
```
Comment (avanhatt) [inline compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:878]: I need to remove this unused param

File: compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs [hunk 4]
```diff
@@ -656,11 +656,25 @@ impl<'tcx> GotocCtx<'tcx> {
...
-                let dst_goto_expr = self.cast_sized_expr_to_unsized_expr(
-                    src_goto_expr.clone(),
-                    src_mir_type,
-                    dst_mir_type,
-                );
+
+                // Check if the cast is from a vtable fat pointer to another
+                // unsized type (which can happen with auto trait fat pointers)
+                let dst_goto_expr =
+                    if let Some(src_mir_dyn_ty) = dyn_from_vtable_fat_pointer(src_mir_type) {
```
Comment (avanhatt) [inline compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:663]: From compiling more std lib cases, this condition might not be complete. Taking another look.

Comment (avanhatt) [reply compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs]: Problem was not the condition, it was another path that assumed cast sources were unsized. Updated in new commit.

File: compiler/rustc_codegen_llvm/src/gotoc/intrinsic.rs [hunk 5]
```diff
@@ -147,7 +147,13 @@ impl<'tcx> GotocCtx<'tcx> {
                     .tcx
                     .const_eval_instance(ty::ParamEnv::reveal_all(), instance, None)
                     .unwrap();
-                let e = self.codegen_const_value(value, self.tcx.types.usize, None);
+                let place_type = self.codegen_ty(self.place_ty(p));
+                let e = self
```
[the remark this answers is not in the document]
Comment (danielsn) [reply compiler/rustc_codegen_llvm/src/gotoc/intrinsic.rs:152]: For example, Rust generates `foo` while CBMC expects `bar`

File: compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs [hunk 6]
```diff
@@ -656,16 +657,32 @@ impl<'tcx> GotocCtx<'tcx> {
...
         }
     }
 
+    fn cast_to_unsized_expr(
+        &mut self,
+        src_goto_expr: Expr,
+        src_mir_type: Ty<'tcx>,
+        dst_mir_type: Ty<'tcx>,
+    ) -> Option<Expr> {
+        // Check if the cast is from a vtable fat pointer to another
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:672]: Can this ever happen between two different slice type unsized? Maybe we should check for that.

**Review by danielsn — CHANGES_REQUESTED** [review]

File: src/test/cbmc/DynTrait/main.rs [hunk 7]
```diff
@@ -24,7 +24,11 @@ impl Animal for Cow {
 
 // Returns some struct that implements Animal, but we don't know which one at compile time.
 fn random_animal(random_number: i64) -> Box<dyn Animal> {
-    if random_number < 5 { Box::new(Sheep {}) } else { Box::new(Cow {}) }
+    if random_number < 5 {
```
Comment (danielsn) [inline src/test/cbmc/DynTrait/main.rs:27]: I can't put this comment on the right line since its not changed in the PR. Why not store the "random number" below, and make sure that we did the right thing based on it.

File: compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs [hunk 8]
```diff
@@ -656,16 +656,32 @@ impl<'tcx> GotocCtx<'tcx> {
...
+        // vtable fat pointer (which can happen with auto trait fat pointers)
+        if is_dyn_trait_fat_pointer(src_mir_type) {
+            self.cast_unsized_dyn_trait_to_unsized_dyn_trait(
+                src_goto_expr.clone(),
+                src_mir_type,
+                dst_mir_type,
+            )
+        } else {
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:679]: If we can add a check that the src isn't a different fat pointer type here, I think we're good to go

**Review by danielsn — COMMENTED** [review]
LGTM, except for one more assertion that would be nice

File: compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs (hunk 8 above)
Comment (avanhatt) [reply compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:679]: Added!

**Review by danielsn — APPROVED** [review]
