### PR TITLE
Fix spurious overflow counter examples. (#558)

### LINKED ISSUE #558: Spurious overflow failures with Result/Error types
I tried this code:

```rust
enum MyError {
    Val1,
    Val2,
}

fn foo(x: u32) -> Result<(), MyError> {
    if x > 10 {
        Err(MyError::Val2)
    } else {
        Ok(())
    }
}

fn bar() -> Result<(), MyError> {
    let x = foo(15)?;

    Ok(x)
}

pub fn main() {
    bar();
}
```

using the following command line invocation:

```
rmc test.rs
```

with RMC version: `7635cfebfa5`

I expected to see this happen: no failures

Instead, this happened: got 2 arithmetic overflow failures:
```
** Results:
/home/ubuntu/tools/rmc/library/core/src/result.rs function <std::result::Result<T, E> as std::ops::Try>::branch
[<std::result::Result<T, E> as std::ops::Try>::branch.assertion.1] line 1903 unreachable code: SUCCESS
[<std::result::Result<T, E> as std::ops::Try>::branch.overflow.1] line 1903 arithmetic overflow on unsigned - in ((unsigned char *)&self)[0] - 2: FAILURE
[<std::result::Result<T, E> as std::ops::Try>::branch.pointer_arithmetic.1] line 1903 pointer arithmetic: dead object in (unsigned char *)&self + 0: SUCCESS
[<std::result::Result<T, E> as std::ops::Try>::branch.pointer_dereference.1] line 1903 dereference failure: dead object in ((unsigned char *)&self)[0]: SUCCESS
[<std::result::Result<T, E> as std::ops::Try>::branch.pointer_arithmetic.2] line 1904 pointer arithmetic: dead object in (unsigned char *)&var_0 + 0: SUCCESS
[<std::result::Result<T, E> as std::ops::Try>::branch.pointer_dereference.2] line 1904 dereference failure: dead object in ((unsigned char *)&var_0)[0]: SUCCESS

/home/ubuntu/tools/rmc/src/test/rmc/Enum/result4.rs function bar
[bar.assertion.1] line 18 unreachable code: SUCCESS
[bar.overflow.1] line 18 arithmetic overflow on unsigned - in ((unsigned char *)&var_2)[0] - 2: FAILURE
[bar.pointer_arithmetic.1] line 18 pointer arithmetic: dead object in (unsigned char *)&var_2 + 0: SUCCESS
[bar.pointer_dereference.1] line 18 dereference failure: dead object in ((unsigned char *)&var_2)[0]: SUCCESS
[bar.pointer_arithmetic.2] line 20 pointer arithmetic: dead object in (unsigned char *)&var_0 + 0: SUCCESS
[bar.pointer_dereference.2] line 20 dereference failure: dead object in ((unsigned char *)&var_0)[0]: SUCCESS

/home/ubuntu/tools/rmc/src/test/rmc/Enum/result4.rs function foo
[foo.pointer_arithmetic.1] line 13 pointer arithmetic: dead object in (unsigned char *)&var_0 + 0: SUCCESS
[foo.pointer_dereference.1] line 13 dereference failure: dead object in ((unsigned char *)&var_0)[0]: SUCCESS

** 2 of 14 failed (2 iterations)
VERIFICATION FAILED
```
The `- 2` in the check:
```
[bar.overflow.1] line 18 arithmetic overflow on unsigned - in ((unsigned char *)&var_2)[0] - 2: FAILURE
```
seems to be coming from the number of values in the enum. The arithmetic overflow checks are not expected in the first place.

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

RMC was treating all arithmetic operations as non-wrapping which was triggering a lot of spurious counter examples. Instead of relying on cbmc generated overflow checks, we are not explicitly encoding checks for non-wrapping operations.

### Resolved issues:

Resolves #558 

### Call-outs:

I created #646 to track implementing more checks that we currently don't support. Except for shift left and division by 0, I believe CBMC doesn't have any mechanism to check them.

### Testing:

* How is this change tested?

I created a bunch of new tests.

* Is this a refactor change?

I guess.

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: compiler/cbmc/src/goto_program/expr.rs [hunk 1]
```diff
@@ -815,7 +815,7 @@ impl Expr {
                     && (lhs.typ.is_pointer() || lhs.typ.is_numeric() || lhs.typ.is_vector())
                     || (lhs.typ.is_pointer() && rhs.typ.is_integer())
             }
-            Plus => {
+            Plus | OverflowMinus | OverflowMult | OverflowPlus => {
```
[the remark this answers is not in the document]
Comment (adpaco-aws) [reply compiler/cbmc/src/goto_program/expr.rs:818]: The argument types have to remain the same for each operation (i.e., `OverflowMinus` goes with `Minus`).

File: compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs [hunk 2]
```diff
@@ -130,6 +130,61 @@ impl<'tcx> GotocCtx<'tcx> {
...
+                    loc,
+                );
+                let expr_place = self.codegen_expr_to_place(p, res.result);
+                Stmt::block(vec![expr_place, check], loc)
+            }};
+        }
+
+        // Intrinsics which encode a SIMD arithmetic operation with overflow check
+        // RMC overflow operations accept SIMD vectors but the results are unsound.
+        // TODO: Create a CBMC issue.
```
Comment (adpaco-aws) [inline compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs:151]: Please create the issue and add it here.

File: src/test/rmc/ArithOperators/wrapping.rs [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+#![feature(core_intrinsics)]
+
+pub fn main() {
+    let a: u8 = rmc::nondet();
+    let b: u8 = rmc::nondet();
+    let sum0 = core::intrinsics::wrapping_add(a, b);
+    let sum1 = a.wrapping_add(b);
+    let sum2 = a.checked_add(b);
+    assert!(sum0 == sum1);
+    assert!(sum1 >= a || sum2.is_none());
```
Comment (zhassan-aws) [inline src/test/rmc/ArithOperators/wrapping.rs:14]: Do you want to add `sum1 >= b` as well?

**Review by zhassan-aws — APPROVED** [review]
Looks great! The new tests are very good!

File: compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs [hunk 4]
```diff
@@ -130,6 +130,61 @@ impl<'tcx> GotocCtx<'tcx> {
...
+                let res = a.$op(b);
+                let expr_place = self.codegen_expr_to_place(p, res);
+                Stmt::block(vec![expr_place, check_stmt], loc)
+            }};
+        }
+
+        // Intrinsics which encode a simple wrapping arithmetic operation
+        macro_rules! codegen_wrapping_op {
+            ($f:ident) => {{ self.binop(p, fargs, |a, b| a.$f(b)) }};
+        }
```
Comment (adpaco-aws) [inline compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs:186]: A few lines below there is `codegen_intrinsic_binop` which does the same thing. Why did you add this?

**Review by adpaco-aws — CHANGES_REQUESTED** [review]
The changes here heavily rely on `-C overflow-checks=on`. Can we add a check to our back-end to ensure the flag is always set?

**Comment by celinval** [comment]
> The changes here heavily rely on `-C overflow-checks=on`. Can we add a check to our back-end to ensure the flag is always set?

Should we allow users to turn them off though? What if I add a check with a warning if the flag is off?

File: compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs (hunk 4 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs:186]: I was trying to make it explicit that this is a wrapping operation. To avoid others to inadvertently using the wrong operation in the future.

I could modify this to just call the binop one or remove this. Any preference?

File: compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs (hunk 2 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs:151]: Oops. Yeah, I need to do that.

File: compiler/cbmc/src/goto_program/expr.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (celinval) [reply compiler/cbmc/src/goto_program/expr.rs:818]: Makes sense. Do you know why the minus has a different retirement?

[the remark this answers is not in the document]
Comment (adpaco-aws) [reply compiler/cbmc/src/goto_program/expr.rs:818]: Yes, minus allows both operands to be pointers because it is valid to compute offsets between them. This does not apply to plus because adding two pointers will likely result in another pointer to who-knows-where.

File: compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs (hunk 2 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs:151]: See my comment above. I did some digging into CBMC and it doesn't look like overflow takes array as argument. I hadn't noticed that CBMC was printing a warning. I wish it would just error out instead.

Anyway, I will update the comment to reflect that.

**Review by adpaco-aws — COMMENTED** [review]
Looking good! Of course, we can change the check in the near future to support other use cases, but I do not feel comfortable with our codegen depending on this flag and not requiring it.

**Review by adpaco-aws — APPROVED** [review]

**Comment by tedinski** [comment]
Doesn't this mean we no longer spot overflows in unsafe code?

**Comment by celinval** [comment]
> Doesn't this mean we no longer spot overflows in unsafe code?

That's a great question! I should definitely add test cases for that.

We are still checking for overflow in unsafe code. Regular arithmetic operations are always checked no matter where they show up in the code.

**Comment by celinval** [comment]
> This should be `check_mul`

I wonder how this test even passed. o.O

**Comment by adpaco-aws** [comment]
> I wonder how this test even passed. o.O

Probably because CBMC is not finding the function to verify and that is understood as a verification failure.
