### PR TITLE
Fix assert!() and panic!() code generation

### LINKED ISSUE #67: Soundness: `codegen_panic` makes a lot of assumptions
`codegen_panic` makes a lot of assumptions about the type of input it gets

### LINKED ISSUE #466: Code location for `assert!(false)` is incorrect.
RMC is giving the wrong code location of assert!(false) statements.

I tried this code:

```rust
fn magic() -> i32 {     // L1
    5                   // L2
}                       // L3
                        // L4
pub fn main() {         // L5
    if magic() == 5 {   // L6
        assert!(false); // L7
    }                   // L8
    println!("Magic!"); // L9
}                       // L10
```

using the following command line invocation:

```
rmc --input dummy.rs
```

with RMC version:

The following output is printed:
```
[main.assertion.1] line 6 assertion failed: false: FAILURE
```

Note that the MIR is correct:
```
> rustc dummy.rs --emit mir
> grep panic dummy.mir
     core::panicking::panic(const "assertion failed: false"); // scope 0 at dummy.rs:7:9: 7:24
```

Root cause:

The assert!() macro is translated to `if !cond { begin_panic; }`. However, for `assert!(false)`, rustc optimizes the generated code and it only emit a `panic` statement.

During RMC code generation of panic statements, we assume that if the basic block only has one predecessor, it is an assertion. There are many cases that this is not true. See [this code](https://github.com/model-checking/rmc/blob/ef758e29c388de215fc88e30b6b39c11db1e1d0f/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/statement.rs#L488).

### LINKED ISSUE #543: Panic and abort should stop the program execution
I tried this code:

```rust
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 OR MIT
//
// rmc-verify-fail

pub fn main() {
    for i in 0..4 {
        if i == 1 {
            panic!("This comes first");
        }
        if i == 2 {
            panic!("This should never happen");
        }
    }
}
```

using the following command line invocation:

```
rmc loop.rs
```

I expected to see this happen: *The first assertion should fail but the second one should be unreachable. The panic call should abort the execution in the second iteration of the loop.*

Instead, this happened: *Both assertions fail. The trace for the second assertion includes the first panic call.*

Note that the same behavior happens if we replace the `panic!()` statement by `process::abort()`.

### LINKED ISSUE #636: An example with a false assertion doesn't terminate
I tried this code:

```rust
#[no_mangle]
fn main() {
    let x: bool = rmc::nondet();
    if x {
        assert!(1 + 1 == 1);
    }
    assert!(1 + 1 == 3);
}
```

using the following command line invocation:

```
rmc test.rs
```

with RMC version: `2141a76f98d`

I expected to see this happen: both assertions fail.

Instead, this happened: it runs forever (CBMC keeps unwinding forever). If I specify an unwinding depth, the unwinding assertion fails:
```
$ rmc test.rs --cbmc-args --unwind 10
.
.
.

** 3 of 78 failed (2 iterations)
VERIFICATION FAILED
[RMC] info: Verification output shows one or more unwinding failures.
[RMC] tip: Consider increasing the unwinding value or disabling `--unwinding-assertions`.
```

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

I refactored how we codegen panic statements so it now it terminate the program per its spec. I have also removed the hack we had to try to get the assert location.

Since we currently do not support stack unwinding, the panic codegen will always terminate immediately and it will not try to unwind the stack. I added an option to RMC to force the compiler to use abort as the panic strategy and a check to rmc codegen that will fail if the user tries to override that.

Another note is that we currently do not support `#[track_caller]` and I have not changed that.

This change fixes #67, fixes #466, fixes #543, and fixes #636. This change also mitigates #545.

### Resolved issues:

Resolves #67
Resolves #466 
Resolves #543 
Resolves #636 

### Call-outs:

I split this into two commits. One with the changes to the compiler and new test cases. The second commit is adjustments to our existing tests.

### Testing:

* How is this change tested? New and old test cases.

* Is this a refactor change? Yes

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: compiler/cbmc/src/goto_program/stmt.rs [hunk 1]
```diff
@@ -207,6 +207,10 @@ impl Stmt {
         )
     }
 
+    pub fn assume_false(loc: Location) -> Self {
```
Comment (danielsn) [inline compiler/cbmc/src/goto_program/stmt.rs:210]: doc comment

File: compiler/rustc_codegen_rmc/src/codegen/span.rs [hunk 2]
```diff
@@ -27,6 +27,16 @@ impl<'tcx> GotocCtx<'tcx> {
         )
     }
 
+    // Get the location of the caller. This will attempt to reach the macro caller.
+    pub fn codegen_caller_span(&self, sp: &Option<Span>) -> Location {
+        if let Some(span) = sp {
+            let topmost = span.ctxt().outer_expn().expansion_cause().unwrap_or(*span);
```
Comment (danielsn) [inline compiler/rustc_codegen_rmc/src/codegen/span.rs:33]: what is this doing?

File: compiler/rustc_codegen_rmc/src/codegen/statement.rs [hunk 3]
```diff
@@ -485,51 +485,34 @@ impl<'tcx> GotocCtx<'tcx> {
...
+        if let Some(values) = fargs[0].struct_expr_values() {
+            if !values.is_empty() {
+                if let ExprValue::AddressOf(msg_value) = values[0].value() {
+                    if let ExprValue::Index { array, .. } = msg_value.value() {
+                        if let ExprValue::StringConstant { s } = array.value() {
+                            msg = s.to_string();
+                        }
+                    }
+                } else {
+                    tracing::error!(?values, "Oh no");
```
Comment (danielsn) [inline compiler/rustc_codegen_rmc/src/codegen/statement.rs:500]: More informative message please?

File: compiler/rustc_codegen_rmc/src/codegen/statement.rs [hunk 4]
```diff
@@ -485,51 +485,34 @@ impl<'tcx> GotocCtx<'tcx> {
...
-                            Stmt::goto(self.current_fn().find_label(alt), Location::none()),
-                        ],
-                        loc,
-                    )
+        let mut msg = String::from(
+            "This is a placeholder message; RMC doesn't support message formatted at runtime",
+        );
+        if let Some(values) = fargs[0].struct_expr_values() {
+            if !values.is_empty() {
+                if let ExprValue::AddressOf(msg_value) = values[0].value() {
```
Comment (danielsn) [inline compiler/rustc_codegen_rmc/src/codegen/statement.rs:493]: Are there any other times we might want to do this? Could be a utility function?

File: compiler/rustc_codegen_rmc/src/codegen/statement.rs [hunk 5]
```diff
@@ -485,51 +485,34 @@ impl<'tcx> GotocCtx<'tcx> {
...
-    // By the time we get this, the string constant has been codegenned.
-    // TODO: make this case also use the Stmt::assert_false() constructor
-    pub fn codegen_assert_false(&mut self, err: Expr, loc: Location) -> Stmt {
-        BuiltinFn::CProverAssert.call(vec![Expr::bool_false(), err], loc.clone()).as_stmt(loc)
+    // Generate code for fatal error which should trigger an assertion failure and abort the
+    // execution.
+    pub fn codegen_fatal_error(&self, msg: &str, span: Option<Span>) -> Stmt {
+        let loc = self.codegen_caller_span(&span);
+        Stmt::block(
+            vec![Stmt::assert_false(msg, loc.clone()), Stmt::assume_false(loc.clone())],
```
Comment (danielsn) [inline compiler/rustc_codegen_rmc/src/codegen/statement.rs:513]: should we `assume(false)` or `abort()`

File: compiler/rustc_codegen_rmc/src/compiler_interface.rs [hunk 6]
```diff
@@ -187,6 +186,16 @@ impl CodegenBackend for GotocCodegenBackend {
     }
 }
 
+fn check_options(session: &Session) {
+    if !session.overflow_checks() {
+        session.err("RMC requires overflow checks in order to provide a sound analysis.")
+    }
+
+    if session.panic_strategy() != PanicStrategy::Abort {
+        session.err("RMC can only handle abort panic strategy (-C panic=abort).")
```
Comment (danielsn) [inline compiler/rustc_codegen_rmc/src/compiler_interface.rs:195]: Link to issue they can +1

File: compiler/rustc_codegen_rmc/src/overrides/hooks.rs [hunk 7]
```diff
@@ -197,9 +197,10 @@ struct Panic;
 
 impl<'tcx> GotocHook<'tcx> for Panic {
     fn hook_applies(&self, tcx: TyCtxt<'tcx>, instance: Instance<'tcx>) -> bool {
-        output_of_instance_is_never(tcx, instance)
-            && (instance_name_is(tcx, instance, "begin_panic")
-                || instance_name_is(tcx, instance, "panic"))
+        let def_id = instance.def.def_id();
+        Some(def_id) == tcx.lang_items().panic_fn()
+            || Some(def_id) == tcx.lang_items().panic_display()
+            || Some(def_id) == tcx.lang_items().begin_panic_fn()
```
Comment (danielsn) [inline compiler/rustc_codegen_rmc/src/overrides/hooks.rs:203]: 👍

File: compiler/rustc_codegen_rmc/src/overrides/hooks.rs [hunk 8]
```diff
@@ -231,15 +232,11 @@ impl<'tcx> GotocHook<'tcx> for Nevers {
...
-        // _target must be None due to how rust compiler considers it
-        Stmt::assert_false(
-            &format!(
-                "a panicking function {} is invoked",
-                with_no_trimmed_paths(|| tcx.tcx.def_path_str(instance.def_id()))
-            ),
-            loc,
-        )
+        let msg = format!(
+            "a panicking function {} is invoked",
```
Comment (danielsn) [inline compiler/rustc_codegen_rmc/src/overrides/hooks.rs:236]: I wonder if we can give a clearer message here

File: src/test/expected/binop/main.rs [hunk 9]
```diff
@@ -56,19 +56,22 @@ fn ibxor_test(a: i32, b: i32, correct: i32, wrong: i32) {
 }
 
 fn main() {
```
Comment (danielsn) [inline src/test/expected/binop/main.rs:58]: IS this to prevent one failure from hiding others?

File: src/test/expected/float-nan/main.rs [hunk 10]
```diff
@@ -6,15 +6,17 @@ fn main() {
...
+        0 => assert!(1.0 / f != 0.0 / f),
+        // should succeed
+        1 => assert!(!(1.0 / f == 0.0 / f)),
+        // should fail
+        2 => assert!(1.0 / f == 0.0 / f),
+        // should fail
+        3 => assert!(0.0 / f == 0.0 / f),
+        // should suceed
+        _ => assert!(0.0 / f != 0.0 / f),
+    }
```
Comment (danielsn) [inline src/test/expected/float-nan/main.rs:21]: would it make sense to have a macro for this pattern

File: src/test/rmc/DynTrait/dyn_fn_param_fail.rs [hunk 11]
```diff
@@ -10,14 +10,18 @@
...
+        rmc::expect_fail(x != 5, "Wrong return");
+    }
 
     /* The function dynamic object has no associated data */
     rmc::expect_fail(size_from_vtable(vtable!(fun)) != 0, "Wrong size");
 }
 
 pub fn unit_to_u32() -> u32 {
-    assert!(false);
+    if rmc::nondet::<bool>() {
```
Comment (danielsn) [inline src/test/rmc/DynTrait/dyn_fn_param_fail.rs:22]: do we need the turbofish here

File: compiler/rustc_codegen_rmc/src/codegen/statement.rs (hunk 3 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/codegen/statement.rs:500]: ooops... That was a debug statement. =)

File: compiler/rustc_codegen_rmc/src/codegen/span.rs (hunk 2 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/codegen/span.rs:33]: It is getting the location of the macro caller. It gets the outer most expansion and get its cause.

File: compiler/rustc_codegen_rmc/src/codegen/statement.rs (hunk 4 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/codegen/statement.rs:493]: I don't know. I figured that this code has a lot of assumptions about the format of the input, so I was thinking about leaving here for now and pulled it out if we start seeing this pattern in other places.

File: compiler/rustc_codegen_rmc/src/codegen/statement.rs (hunk 5 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/codegen/statement.rs:513]: That's a good question. What do you think? I can try it out with abort and see how CBMC behaves.

File: compiler/rustc_codegen_rmc/src/compiler_interface.rs (hunk 6 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/compiler_interface.rs:195]: Sure.

File: compiler/rustc_codegen_rmc/src/overrides/hooks.rs (hunk 8 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/overrides/hooks.rs:236]: Sure. Can I do it in a follow up PR since this will likely impact a lot of expected tests. I think this PR is already big enough.

File: src/test/expected/binop/main.rs (hunk 9 above)
Comment (celinval) [reply src/test/expected/binop/main.rs:58]: Yes. Otherwise everything passed `iadd_test()` becomes unreachable.

File: src/test/expected/float-nan/main.rs (hunk 10 above)
Comment (celinval) [reply src/test/expected/float-nan/main.rs:21]: I figured it wasn't worth the effort. There are a few differences in them and a macro would probably make it harder to read.

File: src/test/rmc/DynTrait/dyn_fn_param_fail.rs (hunk 11 above)
Comment (celinval) [reply src/test/rmc/DynTrait/dyn_fn_param_fail.rs:22]: Oh... that's a good point. I guess because it's inside an `if`, we probably don't. Let me check.

File: compiler/cbmc/src/goto_program/stmt.rs (hunk 1 above)
Comment (celinval) [reply compiler/cbmc/src/goto_program/stmt.rs:210]: For sure!

File: compiler/rustc_codegen_rmc/src/codegen/statement.rs (hunk 3 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/codegen/statement.rs:500]: I'll remove it!

File: compiler/rustc_codegen_rmc/src/codegen/span.rs (hunk 2 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/codegen/span.rs:33]: I think the important part is the expansion_cause() method. This is the doc:
```
    /// Returns span for the macro which originally caused this expansion to happen.
    ///
    /// Stops backtracing at include! boundary.
    pub fn expansion_cause(mut self) -> Option<Span> 
```

This is how other backend engines assemble the Location in PanicInfo when the current function does not have `#[track_caller]` attribute which we currently don't support.

File: compiler/rustc_codegen_rmc/src/codegen/statement.rs (hunk 5 above)
Comment (celinval) [reply compiler/rustc_codegen_rmc/src/codegen/statement.rs:513]: I replaced this by calling `abort()` instead of `assume(false)`, but I still see this message on CBMC output: 
```
aborting path on assume(false) at file <builtin-library-abort> line 6 function abort thread 0
```
So I don't think it will make much difference. I'll use abort() to improve readability.

File: compiler/cbmc/src/goto_program/stmt.rs (hunk 1 above)
Comment (celinval) [reply compiler/cbmc/src/goto_program/stmt.rs:210]: I'm actually removing this since I am adding a builtin abort()

File: compiler/rustc_codegen_rmc/src/codegen/statement.rs (hunk 4 above)
Comment (tedinski) [reply compiler/rustc_codegen_rmc/src/codegen/statement.rs:493]: I think Jai had a utility function that does this in his first PR (that's still open). Maybe just steal it from there?

File: src/test/rmc/Options/check_tests.rs [hunk 12]
```diff
@@ -4,7 +4,7 @@
 // Check that we can verify test harnesses using the --tests argument.
 // Note: We need to provide the compile-flags because compile test runs rustc directly and via rmc.
 
-// compile-flags: --test
+// compile-flags: --test --C panic=abort
```
Comment (tedinski) [inline src/test/rmc/Options/check_tests.rs:7]: Is this needed?

File: compiler/rustc_codegen_rmc/src/codegen/span.rs (hunk 2 above)
Comment (tedinski) [reply compiler/rustc_codegen_rmc/src/codegen/span.rs:33]: I agree this function could use an extensive doc comment. It looks like you found a really great solution compared to our original hack, so helping us use this function more in the future would be awesome.

File: src/test/expected/float-nan/main.rs (hunk 10 above)
Comment (tedinski) [reply src/test/expected/float-nan/main.rs:21]: I wonder if we should have the original, primitive cbmc assert available still.

Then our tests could still be straight-line code, just using `rmc::assert()` instead of `assert!`

Comment (celinval) [reply src/test/expected/float-nan/main.rs:21]: I was thinking about adding a function rmc::check() that had the behaviour you mentioned. What do you think? I would prefer not having two types of assert.

That said, I would prefer adding it in a different PR.

Comment (celinval) [reply src/test/expected/float-nan/main.rs:21]: Also, once we have the `#[proof]` attribute integrated, we should be able to easily split tests like this into multiple harnesses in the same file.

File: src/test/rmc/Options/check_tests.rs (hunk 12 above)
Comment (celinval) [reply src/test/rmc/Options/check_tests.rs:7]: Let me double check. I think you are correct though.

File: src/test/expected/float-nan/main.rs (hunk 10 above)
Comment (tedinski) [reply src/test/expected/float-nan/main.rs:21]: I'm cool with a different name (brainstorming: `rmc::probe`? `check` also seems good) and in a follow up PR.

File: src/test/rmc/DynTrait/dyn_fn_param_fail.rs (hunk 11 above)
Comment (tedinski) [reply src/test/rmc/DynTrait/dyn_fn_param_fail.rs:22]: was it necessary?

File: src/test/rmc/Options/check_tests.rs (hunk 12 above)
Comment (tedinski) [reply src/test/rmc/Options/check_tests.rs:7]: was it necessary?

**Review by tedinski — APPROVED** [review]
I think this is good to merge. I really want `rmc::check` or whatever we call it, but whenever we get to it I guess. :)

There were two very minor things I didn't see addressed that I added comments to, also.

File: src/test/expected/float-nan/main.rs (hunk 10 above)
Comment (celinval) [reply src/test/expected/float-nan/main.rs:21]: I created https://github.com/model-checking/rmc/issues/695 to capture the work.

**Comment by celinval** [comment]
> I think this is good to merge. I really want `rmc::check` or whatever we call it, but whenever we get to it I guess. :)
> 
> There were two very minor things I didn't see addressed that I added comments to, also.

My bad. I had missed them. Thanks for pointing it out.

**Review by danielsn — APPROVED** [review]
