### PR TITLE
Fix vtable size check for never

### LINKED ISSUE #421: Failed assertion: Correct CBMC vtable size for Never
With some combinations of traits and the `Never` type, the CBMC-time sanity check assert fails because you cannot take an object size of `void`. 

Breaking this into its own PR to land since it's coming up outside of drop work.

### PR DESCRIPTION
**Pull request by avanhatt**
### Description of changes: 

With some combinations of traits and the Never type, the CBMC-time sanity check assert fails because you cannot take an object size of void.

Breaking this into its own PR to land since it's coming up outside of drop work.

### Resolved issues:

Resolves #421

### Call-outs:

Working on getting a small example now, but a little difficulty since this happens in external crate code.

### Testing:

* How is this change tested?

Existing tests, working on minimal example.

* Is this a refactor change?

No.

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs [hunk 1]
```diff
@@ -766,10 +766,17 @@ impl<'tcx> GotocCtx<'tcx> {
         // Insert a CBMC-time size check, roughly:
         //     <Ty> local_temp = nondet();
         //     assert(__CPROVER_OBJECT_SIZE(&local_temp) == vt_size);
-        let temp_var = self.gen_temp_variable(ty, Location::none()).to_expr();
+        let temp_var = self.gen_temp_variable(ty.clone(), Location::none()).to_expr();
         let decl = Stmt::decl(temp_var.clone(), None, Location::none());
-        let check = Expr::eq(Expr::object_size(temp_var.address_of()), vt_size.clone());
-        let assert_msg = format!("Correct CBMC vtable size for {:?}", operand_type.kind());
+        let cbmc_size = if ty.clone().is_empty() {
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:771]: This clone should be unneccessary

File: compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs [hunk 2]
```diff
@@ -766,10 +766,17 @@ impl<'tcx> GotocCtx<'tcx> {
...
+            // CBMC errors on passing a pointer to void to __CPROVER_OBJECT_SIZE, so just pass 0
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:772]: Are we guaranteed this is correct? Or is this a temporary hack?

Comment (avanhatt) [reply compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs]: Added an assert for the `Never` case and a link showing that we do know the size is 0. This way, will get a more detailed error if this fails again for a different type.

**Review by danielsn — APPROVED** [review]
