### PR TITLE
Complete count intrinsics codegen and testing

### LINKED ISSUE #26: Simplify code for count intrinsics in next CBMC version
There are a couple of PRs that will add support for count builtins in CBMC. This will allow the count intrinsics code in RMC to be simplified and its regression tests to be enabled.

### PR DESCRIPTION
**Pull request by adpaco-aws**
### Description of changes: 

The contributions in this PR are:
 1. Completes the codegen for count intrinsics
 2. Extends the regression script to invoke rmc with an extra CBMC arg. `--bound-check` required by these tests
 3. Enables both positive and negative tests for count intrinsics (the negative are the ones which require the mentioned flag)
 4. Upgrades CI to CBMC 5.30.1, also required by the tests

### Resolved issues:

Resolves #26 

### Testing:

* How is this change tested? Running the full regression suite.

* Is this a refactor change? No

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/irep/to_irep.rs [hunk 1]
```diff
@@ -278,15 +278,15 @@ impl ToIrep for ExprValue {
...
+                    if *allow_zero { Irep::zero() } else { Irep::one() }
                 )],
             },
             ExprValue::UnOp { op: UnaryOperand::CountTrailingZeros { allow_zero }, e } => Irep {
                 id: IrepId::CountTrailingZeros,
                 sub: vec![e.to_irep(mm)],
                 named_sub: btree_map![(
                     IrepId::CBoundsCheck,
-                    if *allow_zero { Irep::one() } else { Irep::zero() }
+                    if *allow_zero { Irep::zero() } else { Irep::one() }
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/irep/to_irep.rs:289]: Oof

**Review by danielsn — APPROVED** [review]
