### PR TITLE
Move 1 rust-test to compiletest.

### LINKED ISSUE #121: Start porting regression tests to compiletest
We can integrate our regression tests with compiletest. Find out how and port a few of them to compiletest.

### PR DESCRIPTION
**Pull request by bdalrhm**
### Description of changes: 

This PR moves `rust-tests/cbmc-reg/Bool-BoolOperators/main.rs` to `src/test/cbmc/Bool-BoolOperators/main.rs` and modifies bootstrap and compiletest source files to run the regression test with `x.py`.

### Resolved issues:

Resolves #121

### Testing:

* How is this change tested?
  * A new line is added to `scripts/rmc-regression.sh` to test the moved regression

* Is this a refactor change?
  * No

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: src/test/cbmc/Closure/main.rs [hunk 1]
```diff
@@ -0,0 +1,47 @@
+// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
```
Comment (adpaco-aws) [inline src/test/cbmc/Closure/main.rs:1]: Find another passing test that is simpler. Do not add, move it.

File: src/bootstrap/test.rs [hunk 2]
```diff
@@ -1212,6 +1214,12 @@ note: if you're sure you want to do this, please open an issue as to why. In the
         cmd.arg("--run-lib-path").arg(builder.sysroot_libdir(compiler, target));
         cmd.arg("--rustc-path").arg(builder.rustc(compiler));
 
+        // pass the path to the RMC script directory as an option to compiletest
```
Comment (adpaco-aws) [inline src/bootstrap/test.rs:1217]: Capital letter please.

**Review by adpaco-aws — CHANGES_REQUESTED** [review]
LGTM, but it could use more comments. Also, let's starting moving test and not just add them.

File: src/tools/compiletest/src/runtest.rs [hunk 3]
```diff
@@ -2369,6 +2386,15 @@ impl<'test> TestCx<'test> {
         }
     }
 
+    fn run_rmc_test(&self) {
+        let mut rmc = Command::new("rmc");
+        rmc.arg(&self.testpaths.file);
+        let proc_res = self.compose_and_run_compiler(rmc, None);
```
[the remark this answers is not in the document]
Comment (bdalrhm) [reply src/tools/compiletest/src/runtest.rs:2394]: Done.

File: src/tools/compiletest/src/runtest.rs [hunk 4]
```diff
@@ -2369,6 +2386,15 @@ impl<'test> TestCx<'test> {
...
+        if !proc_res.status.success() {
+            self.fatal_proc_rec("compilation failed!", &proc_res);
+        }
+    }
```
[the remark this answers is not in the document]
Comment (bdalrhm) [reply src/tools/compiletest/src/runtest.rs]: Done. Please take a look.

File: src/tools/compiletest/src/runtest.rs [hunk 5]
```diff
@@ -1791,6 +1792,22 @@ impl<'test> TestCx<'test> {
...
         let aux_dir = self.build_all_auxiliary(&mut rustc);
+
+        if (self.config.mode == RMC) {
+            // add the RMC scripts directory to the PATH environment variable
+            if let Some((key, val)) = env::vars().find(|(key, _)| key == "PATH") {
+                rustc.env(
+                    String::from("PATH"),
+                    format!("{}:{}", self.config.rmc_dir_path.to_str().unwrap(), val),
+                );
+            } else {
```
[the remark this answers is not in the document]
Comment (bdalrhm) [reply src/tools/compiletest/src/runtest.rs]: Done.

File: src/tools/compiletest/src/runtest.rs [hunk 6]
```diff
@@ -2369,6 +2370,33 @@ impl<'test> TestCx<'test> {
...
+        if let Some((key, val)) = env::vars().find(|(key, _)| key == "PATH") {
+            // Add the RMC scripts directory to the PATH.
+            rmc.env(key, format!("{}:{}", self.config.rmc_dir_path.to_str().unwrap(), val));
+        } else {
+            // Otherwise, insert PATH as a new enviornment variable and set its value to the RMC scripts directory.
+            rmc.env(String::from("PATH"), String::from(self.config.rmc_dir_path.to_str().unwrap()));
+        }
+    }
+
+    /// Runs rmc model checker on the test file specified by `self.testpaths.file`. A "verification failed!" error is printed to the stdout if verfication fails.
```
Comment (adpaco-aws) [inline src/tools/compiletest/src/runtest.rs:2385]:
```suggestion
    /// Runs RMC on the test file specified by `self.testpaths.file`.
    /// An error message is printed to stdout if verfication fails.
```

File: src/tools/compiletest/src/runtest.rs [hunk 7]
```diff
@@ -2369,6 +2370,33 @@ impl<'test> TestCx<'test> {
...
+    fn run_rmc_test(&self) {
+        // Other modes call self.compile_test(...). However, we cannot call it here for two reasons:
+        // 1. It calls rustc instead of rmc, and
+        // 2. It may pass some options that do not make sense for rmc.
+        // So, we create our own command to execute rmc and pass it to self.compose_and_run_compiler(...) directly.
```
Comment (adpaco-aws) [inline src/tools/compiletest/src/runtest.rs:2390]:
```suggestion
        // Other modes call self.compile_test(...). However, we cannot call it here for two reasons:
        // 1. It calls rustc instead of RMC
        // 2. It may pass some options that do not make sense for RMC
        // So we create our own command to execute RMC and pass it to self.compose_and_run_compiler(...) directly.
```

**Review by adpaco-aws — CHANGES_REQUESTED** [review]
Looks great! Just a few suggestions.

**Review by adpaco-aws — APPROVED** [review]
