### PR TITLE
Fix extern statics to be codegenned as extern

### LINKED ISSUE #369: Generated symbols for statics are sometimes not labelled correctly.
Two cases here:

1) `SizeAndAlignOfDst/main_fail.rs`

Running `rmc --keep-temps main_fail.rs` and then opening `main_fail.json`, we find the following symbol:
```
    "_ZN3std9panicking11panic_count18GLOBAL_PANIC_COUNT17hbb0e4a14d9617703E": {
      "baseName": "_ZN3std9panicking11panic_count18GLOBAL_PANIC_COUNT17hbb0e4a14d9617703E",
      "isAuxiliary": false,
      "isExported": false,
      "isExtern": false,
      "isFileLocal": false,
      "isInput": false,
      "isLvalue": true,
      "isMacro": false,
      "isOutput": false,
      "isParameter": false,
      "isProperty": false,
      "isStateVar": true,
      "isStaticLifetime": false,
      "isThreadLocal": true,
      "isType": false,
      "isVolatile": false,
      "isWeak": false,
      ...
```

which comes from the Rust library: [Rust Internal Docs](https://stdrs.dev/nightly/x86_64-pc-windows-gnu/std/panicking/panic_count/static.GLOBAL_PANIC_COUNT.html)

I believe this should have, instead:
```
      "isStaticLifetime": true,
      "isThreadLocal": false,
```

2) The following code (`main.rs`):

```
static A: u32 = 1;
static mut B: u32 = 2;

extern "C" {
    static C: u32;
    static mut D: u32;
}

fn main() {
    static E: u32 = 5;
    static mut F: u32 = 6;

    unsafe {
        assert!(A == 1);
        assert!(B == 2);
        assert!(C == 3);
        assert!(D == 4);
        assert!(E == 5);
        assert!(F == 6);
    }
}
```

Running `rmc --keep-temps main.rs` and then opening `main.json`, we find the a symbol for each static. All of the fields are the same as above except `"baseName"`, and possibly `"isStaticLifetime"` and `"isThreadLocal"`.

The ones with `isStaticLifetime` as `true` and `isThreadLocal` as `false` are `A`, `B`, `E`,  and `F`. 
The ones with `isStaticLifetime` as `false` and `isThreadLocal` as `true` are `C` and `D`.

---

It looks from the above examples that statics within `extern` blocks and that are in the Rust library are given incorrect tags.

Note that if we don't include the assertions in the second example, then `A`, `B`, `E`, and `F` symbols are all still generated, but `C` and `D` are not.

### PR DESCRIPTION
**Pull request by vecchiot-aws**
### Description of changes: 

Currently, given code like the following, the symbol for `A` is not labelled as extern. This PR fixes that, and also cleans up how static variable symbols are created.

```Rust
extern "C" {
    static mut A: u32;
}
```

### Resolved issues:

Resolves #369 

### Testing:

* How is this change tested? Existing regression suite.

* Is this a refactor change? None.

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/gotoc/operand.rs [hunk 1]
```diff
@@ -323,20 +323,28 @@ impl<'tcx> GotocCtx<'tcx> {
...
-                    Symbol::variable(
-                        name.clone(),
-                        name.clone(),
-                        tcx.codegen_ty(instance.ty(tcx.tcx, ty::ParamEnv::reveal_all())),
-                        tcx.codegen_span2(&span),
+                let instance = Instance::mono(self.tcx, def_id);
+
+                let sym = self.ensure(&self.symbol_name(instance), |ctx, name| {
+                    // check if this static is extern
+                    // TODO: copying what cranelift did here
```
Comment (avanhatt) [inline compiler/rustc_codegen_llvm/src/gotoc/operand.rs:332]: Nit: remove `TODO`, reference Cranelift file

File: compiler/rustc_codegen_llvm/src/gotoc/operand.rs [hunk 2]
```diff
@@ -323,20 +323,28 @@ impl<'tcx> GotocCtx<'tcx> {
...
+                    let rlinkage = ctx.tcx.codegen_fn_attrs(def_id).linkage;
+
+                    // we believe rlinkage some => not extern
+                    assert!(rlinkage.is_none()); // leave assert, add comment to make ticket
```
Comment (avanhatt) [inline compiler/rustc_codegen_llvm/src/gotoc/operand.rs:336]: Add issue

**Review by avanhatt — CHANGES_REQUESTED** [review]

**Review by avanhatt — APPROVED** [review]

**Review by danielsn — APPROVED** [review]
