### PR TITLE
Ensure only Rust files are parsed in Litani runs

### LINKED ISSUE #498: Invalid UTF-8 in dashboard runs
When generating the dashboard I got the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', src/tools/dashboard/src/util.rs:135:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


command did not execute successfully: "/Users/accorell/rmc-dash/build/x86_64-apple-darwin/stage1/bin/dashboard"
expected success, got: exit status: 101



1 command(s) did not execute successfully:

  - "/Users/accorell/rmc-dash/build/x86_64-apple-darwin/stage1/bin/dashboard"

Build completed unsuccessfully in 0:02:52
```

### PR DESCRIPTION
**Pull request by adpaco-aws**
### Description of changes: 

These changes ensure that only Rust files are parsed in Litani runs. Other files in `src/test/dashboard` (e.g., `.goto` or `.json`) would cause the "invalid UTF-8" error from issue #498.

### Resolved issues:

Resolves #498 

### Call-outs:

Also removes a couple of variables that were not being used (and causing warnings).

### Testing:

* How is this change tested? Existing regression + dashboard run.

* Is this a refactor change? No.

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: src/tools/dashboard/src/books.rs [hunk 1]
```diff
@@ -449,8 +447,12 @@ fn litani_run_tests() {
     for entry in WalkDir::new(dashboard_dir) {
         let entry = entry.unwrap().into_path();
         if entry.is_file() {
-            let test_props = util::parse_test_header(&entry);
-            util::add_test_pipeline(&mut litani, &test_props);
+            // Ensure that we parse only Rust files by checking their extension
+            let entry_ext = &entry.extension().and_then(OsStr::to_str);
+            if entry_ext.is_some() && entry_ext.unwrap() == "rs" {
```
Comment (danielsn) [inline src/tools/dashboard/src/books.rs:452]: `if let Some("rs") = entry_ext {`
