### PR TITLE
Regression test for codegen'ing Firecracker

### LINKED ISSUE #262: Create regression workflow for codegen of virtio module

### PR DESCRIPTION
**Pull request by nchong-at-aws**
### Description of changes: 

No changes to RMC. Add codegen test for Firecracker virtio module to regression.

### Resolved issues:

Resolves #262

### Checklist
- [X] Each commit message has a non-empty body, explaining why the change was made
- [X] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: scripts/codegen-firecracker.sh [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+# Test for platform
+platform=`uname -sp`
+if [[ $platform != "Linux x86_64" ]]; then
+  echo "Codegen script only works on Linux x86 platform"
+  exit 0
+fi
+
+# At the moment, we only test codegen for the virtio module
+cd /tmp
+git clone https://github.com/firecracker-microvm/firecracker.git
```
Comment (danielsn) [inline scripts/codegen-firecracker.sh:14]: We might want to pin this to a particular commit?

File: scripts/rmc-regression.sh [hunk 2]
```diff
@@ -22,3 +22,6 @@ check-cbmc-viewer-version.py --major 2 --minor 5
 # Standalone rmc tests, expected tests, and cargo tests
 ./x.py build -i --stage 1 library/std ${EXTRA_X_PY_BUILD_ARGS}
 ./x.py test -i --stage 1 cbmc firecracker prusti smack expected cargo-rmc
+
+# Check codegen of firecracker
+$SCRIPT_DIR/codegen-firecracker.sh
```
Comment (adpaco-aws) [inline scripts/rmc-regression.sh:27]: What about adding this as a separate workflow?

**Review by adpaco-aws — COMMENTED** [review]
Seems we have regressed already :(

File: scripts/rmc-regression.sh (hunk 2 above)
Comment (nchong-at-aws) [reply scripts/rmc-regression.sh:27]: Yes, can do. I was putting it into the regression to avoid rebuilding RMC in two different flows. Is there a way we can share artifacts across?

Comment (adpaco-aws) [reply scripts/rmc-regression.sh:27]: We have been looking into this but we are not sure if it's good for caching RMC builds: https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts

But since it's not clear, any solution would be fine with me. I would like to revisit in the future to have 1 workflow that builds and multiple workflows which depend on that one to execute the regression.

File: scripts/codegen-firecracker.sh (hunk 1 above)
Comment (robin-aws) [reply scripts/codegen-firecracker.sh:14]: Could this be a submodule instead? That's a standard way to pin a specific commit, plus tooling support like Dependabot. :)

**Comment by avanhatt** [comment]
It looks like the CI failure might be fixed in https://github.com/model-checking/rmc/issues/259, merging to rerun tests.

**Comment by avanhatt** [comment]
Filed to track new crash: https://github.com/model-checking/rmc/issues/272

**Comment by avanhatt** [comment]
Added a commit that appears to fix the regression; if we want to keep this PR to no changes to RMC I can break it off into a separate PR.

File: scripts/codegen-firecracker.sh [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+cd firecracker/src/devices/src/virtio/
+RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc --cfg=rmc" RUSTC=rmc-rustc cargo build --target x86_64-unknown-linux-gnu -j1
```
Comment (adpaco-aws) [inline scripts/codegen-firecracker.sh:16]: Do we need `-j1` here?

**Review by adpaco-aws — COMMENTED** [review]
I have changed my mind: Adding to normal regression is fine with me.

File: scripts/codegen-firecracker.sh (hunk 3 above)
Comment (nchong-at-aws) [reply scripts/codegen-firecracker.sh:16]: Nope, we can remove. This does make errors easier to see when we get a failure though (since we parse each package serially)

**Comment by nchong-at-aws** [comment]
Ah, we need the copyright check to ignore Firecracker

**Comment by adpaco-aws** [comment]
I'm fine with overriding the copyright check for this PR. The regression failure is a concern though, I think it is due to `rustfmt` so please try to exclude it as we do for other submodules in `rustfmt.toml`.

**Comment by nchong-at-aws** [comment]
Rustfmt now ignores firecracker submodule. Will deal with the copyright check next.

**Review by avanhatt — APPROVED** [review]
Looks good to me!

**Review by adpaco-aws — APPROVED** [review]
