### PR TITLE
Make `--gen-c-runnable` produce runnable C code

### LINKED ISSUE #237: Output of gen-c is not valid C code
Running RMC with the `--gen-c` flag produces a C-like program output, but the outputted file is not valid C code.

Invalid parts:
- `src/test/cbmc/FunctionCall_Ret-Param/main.rs`
  - `main` can't return `struct Unit`, must return `int`
  - Tuple name (e.g. `struct (u32, bool)`) invalid
  - For tuples, `.0`, `.1`, etc. are invalid field names; replace with `._1`?
  - `overflow` is not defined for addition, etc.
  - `memcpy` and `memmove` are macros, and so their headers cause compile errors
  - `nondet_<k>()` is not defined
- `src/test/cbmc/FunctionCall_Ret-Param/main.rs` + print at end
  - Array name (e.g. `struct [&str]` or `struct [&str; 2]`) invalid
  - Qualified type name (e.g. `std::fmt::ArgumentV1`) invalid
  - Dynamic types (e.g. `dyn std::fmt::Write::vtable`) invalid
  - Parameterized types (e.g. `std::option::Option<usize>`) invalid
  - Union types (e.g. `Option-union`) invalid
  - `byte_extract_little_endian` is not defined
- `src/test/cbmc/FatPointers/boxtrait.c`
  - `_RINvNtCsj5Zaw82J3PU_5alloc5alloc8box_freeDNtCs21hi0yVfW1J_8boxtrait5TraitEL_NtB2_6GlobalEBG_(var_1._0, var_1._1);`
    - Use `->` instead of `.`
  - `OBJECT_SIZE` is not defined
  - `dyn_Trait__vtable` has wrong field names `.__Trait__get` -> `.get`, `.__Trait__increment` -> `.increment`

### PR DESCRIPTION
**Pull request by vecchiot-aws**
### Description of changes: 

A PR introducing a `--gen-c-runnable` flag which produces a runnable C program from the compiled goto program. The existing `--gen-c` flag acts as a starting point, but there are a few issues listed in #237 that prevent the generated C file from compiling.

The change builds off of the visitor pattern introduced by #321, creating a symbol table transformer that normalizes identifiers and perform some extra processing on the symbol table.

(Replaces #317.)

### Resolved issues:

Partially resolves #237 (possibly fully after more changes.)

### Call-outs:

Todo:

- [x] Generate default bodies for `nondet_<k>()` functions.
- [ ] Generate `nondet_<k>()` functions from a sample trace.
- [x] Verify definition for `overflow`
- [x] Fix field access in `src/test/cbmc/FatPointers/boxtrait.c`
- [x] Set up distinct flags for readable and runnable gen-c
- [ ] Figure out testing strategy
- [x] Documentation
- [ ] Clean up commits

### Testing:

* How is this change tested? Existing regression suite.

* Is this a refactor change? No.

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by vecchiot-aws** [comment]
To fix:

- [ ] CodegenConstValue/u128.rs
  - `error: integer literal is too large to be represented in any integer type`
- [ ] Strings/fixme_boxed_str.rs
  - Something to do with pointers
- [ ] BitManipulation/Stable/fixme_main_fail.rs
  - `error: implicit declaration of function 'irep' is invalid in C99`
- [ ] BitManipulation/Unstable/Rotate/main.rs
  - `error: implicit declaration of function 'irep' is invalid in C99`
- [ ] Asm/main_fixme.rs
  - No default value for type `empty`
- [ ] ForeignItems/main.rs
  - Static extern variables not declared
- [ ] Cast/cast_abstract_args_to_concrete.rs
  - `powi` and `powif` not defined
- [ ] Cast/from_be_bytes.rs
  - Something to do with overlapping parameter and local variable names?
- [ ] SizeAndAlignOfDst/main_fail.rs
  - `__CPROVER_atomic_begin` and `__CPROVER_atomic_end` 
  - `error: use of undeclared identifier '_ZN3std9panicking11panic_count18GLOBAL_PANIC_COUNT17hbb0e4a14d9617703E'`
- [ ] SizeAndAlignOfDst/main.rs
  - `__CPROVER_atomic_begin` and `__CPROVER_atomic_end` 
- [ ] FatPointers/boxmuttrait.rs
  - `byte_extract_little_endian` defined wrong
- [ ] SIMD/Operators/main.rs
  - `error: assigning to 'long *' from incompatible type '__attribute__((__vector_size__(2 * sizeof(long)))) long'`
  - `error: address of vector element requested`
- [ ] Atomics/*
  - `__CPROVER_atomic_begin` and `__CPROVER_atomic_end` 
- [ ] Vectors/fixme_main.rs
  - ?
- [ ] DynTrait/*
  - `error: indirection requires pointer operand ('struct _closure_DynTrait_boxed_closure_fail_fixme_rs_14_44__16_6_' invalid)`
- [ ] CopyIntrinsics/main.rs
  - `default` is a keyword
  - Something to do with pointers
- [ ] PointerOffset/*
  - `error: implicit declaration of function 'POINTER_OBJECT' is invalid in C99`
- [ ] Intrinsics/fixme_catch_unwind.rs
  - Something to do with overlapping parameter and local variable names?
- [ ] VolatileIntrinsics/main.rs
  - `default` is a keyword
  - Something to do with pointers

**Comment by vecchiot-aws** [comment]
Simplified version of `error: assigning to 'long *' from incompatible type '__attribute__((__vector_size__(2 * sizeof(long)))) long'`

```
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 OR MIT
#![feature(repr_simd)]

#[repr(simd)]
#[allow(non_camel_case_types)]
#[derive(PartialEq)]
pub struct i64x2(i64, i64);

fn main() {
    assert!(i64x2(0, 0) == i64x2(0, 0));
}
```

**Comment by vecchiot-aws** [comment]
Changes:
- Normalizing identifiers
    - Replace non-alphanumeric + "_" + "$" with "_"
    - Add "_" before name if starts with number
    - Add "_" to key words
    - If overlapping output names, add "_<k>"

- Transform names
    - Symbol name
    - Parameters
    - Member access to structs/unions
    - Symbol expr
    - Structs
        - Struct name
        - Struct component
        - Struct type
    - Unions
        - Union name
        - Union field
        - Union component
        - Union type
    - Goto/labels

- Replacements
    - Big nums
        - If a constant goes above u64::MAX, break into (a * u64::MAX + b)
    - Bin ops
        - Replace `lhs ==> rhs` with `!lhs || rhs`
    - Vector indexing
        - Cast vector to array, and then index
    - Replace `main` with `main_` so we can create `main` with `int` return type

- Nondet
    - Replace `nondet` calls with calls to custom `non_det` functions with default return values
        - Except padding fields, since they are ignored, and ignored nondets are not genned in --dump-c
    - Fill in missing extern functions with calls to nondet

- C library
    - Manually define some CPROVER stuff

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/common.rs [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+            format!("infinite_array_of_{}", type_to_string(typ.as_ref()))
+        }
+        Type::Pointer { typ } => format!("pointer_to_{}", type_to_string(typ.as_ref())),
+        Type::Signedbv { width } => format!("signed_bv_{}", width),
+        Type::Struct { tag, .. } => format!("struct_{}", tag),
+        Type::StructTag(tag) => format!("struct_tag_{}", tag),
+        Type::Union { tag, .. } => format!("union_{}", tag),
+        Type::UnionTag(tag) => format!("union_tag_{}", tag),
+        Type::Unsignedbv { width } => format!("unsigned_bv_{}", width),
+        Type::VariadicCode { parameters, return_type } => {
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/common.rs:39]: this might be worth an example

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 2]
```diff
@@ -0,0 +1,277 @@
...
+};
+use super::super::Transformer;
+use super::common::type_to_string;
+use num::bigint::BigInt;
+use rustc_data_structures::fx::FxHashMap;
+
+/// Create an expr from an int constant using only values <= u64::MAX.
+fn bignum_to_expr(num: &BigInt, typ: &Type) -> Expr {
+    // CInteger types should already be valid in C
+    if matches!(typ, Type::CInteger(_)) {
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:19]: `typ.is_cinteger()`

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 3]
```diff
@@ -0,0 +1,277 @@
...
+use super::super::super::{
+    BinaryOperand, CIntType, Expr, Location, Parameter, Stmt, Symbol, SymbolTable, SymbolValues,
+    Type,
+};
+use super::super::Transformer;
+use super::common::type_to_string;
+use num::bigint::BigInt;
+use rustc_data_structures::fx::FxHashMap;
+
+/// Create an expr from an int constant using only values <= u64::MAX.
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:16]: This is needed because gcc allows 128 bit int variables, but not 128 bit constants

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 4]
```diff
@@ -0,0 +1,277 @@
...
+    if let Some(width) = typ.width() {
+        if width <= 64 {
+            return Expr::int_constant(num.clone(), typ.clone());
+        }
+    }
+
+    // Only types that should be left are i128 and u128
+    assert_eq!(typ.width(), Some(128), "Unexpected int width: {:?}", typ.width());
+
+    let left_mask = BigInt::from(u64::MAX).shl(64);
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:33]: Add pseudocode showing what happens here

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 5]
```diff
@@ -0,0 +1,277 @@
...
+    let right_mask = BigInt::from(u64::MAX);
+
+    let unsigned_typ = match typ {
+        Type::Unsignedbv { .. } => typ.clone(),
+        Type::Signedbv { width } => Type::unsigned_int(*width),
+        _ => panic!("Unexpected type in bignum_to_expr: {:?}", typ),
+    };
+    let left_half: BigInt = num.bitand(left_mask);
+    let right_half = num.bitand(right_mask);
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:42]: Why typedef on only one of these

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 6]
```diff
@@ -0,0 +1,277 @@
...
+    Expr::int_constant(left_half.shr(64), unsigned_typ.clone())
+        .shl(Expr::int_constant(64, Type::c_int()))
+        .bitor(Expr::int_constant(right_half, unsigned_typ))
+        .cast_to(typ.clone())
+}
+
+/// Struct for handling the expression replacement transformations for --gen-c-runnable.
+pub struct ExprTransformer {
+    new_symbol_table: SymbolTable,
+    empty_statics: FxHashMap<String, Expr>,
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:53]: Comment explaining this

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 7]
```diff
@@ -0,0 +1,277 @@
...
+impl ExprTransformer {
+    /// Replace expressions which lead to invalid C with alternatives.
+    pub fn transform(original_symbol_table: &SymbolTable) -> SymbolTable {
+        let new_symbol_table = SymbolTable::new(original_symbol_table.machine_model().clone());
+        ExprTransformer { new_symbol_table, empty_statics: FxHashMap::default() }
+            .transform_symbol_table(original_symbol_table)
+    }
+
+    /// Extract `empty_statics` map for final processing.
+    pub fn empty_statics_owned(&mut self) -> FxHashMap<String, Expr> {
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:65]: This doesn't need to be a `pub `

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 8]
```diff
@@ -0,0 +1,277 @@
...
+        std::mem::replace(&mut self.empty_statics, FxHashMap::default())
+    }
+
+    /// Add identifier to a transformed parameter if it's missing.
+    /// Necessary when function wasn't originally a definition.
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:70]: e.g. extern functions. Explain why you need to give them function bodies.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 9]
```diff
@@ -0,0 +1,277 @@
...
+        &mut self,
+        _typ: &Type,
+        op: &BinaryOperand,
+        lhs: &Expr,
+        rhs: &Expr,
+    ) -> Expr {
+        let lhs = self.transform_expr(lhs);
+        let rhs = self.transform_expr(rhs);
+
+        match op {
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:116]: Make `binop` public, and this becomes a 2 liner :)

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 10]
```diff
@@ -0,0 +1,277 @@
...
+        }
+    }
+
+    /// Prevent error for too large constants with u128.
+    fn transform_expr_int_constant(&mut self, typ: &Type, value: &BigInt) -> Expr {
+        let transformed_typ = self.transform_type(typ);
+        bignum_to_expr(value, &transformed_typ)
+    }
+
+    /// When indexing into a SIMD vector, cast to a pointer first to make legal indexing in C.
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:156]: give c pseudocode

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 11]
```diff
@@ -0,0 +1,277 @@
...
+            let new_typ = self.transform_type(&symbol.typ);
+            let new_value = self.transform_value(&symbol.value);
+            new_symbol.typ = new_typ;
+            new_symbol.value = new_value;
+        }
+
+        new_symbol
+    }
+
+    /// Move `main` to `main_`, and create a wrapper `main` to initialize statics and return `int`.
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:230]: This will happen in its own pass

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs [hunk 12]
```diff
@@ -0,0 +1,245 @@
...
+    DatatypeComponent, Expr, Location, Parameter, Stmt, Symbol, SymbolTable, Type,
+};
+use super::super::Transformer;
+use rustc_data_structures::fx::{FxHashMap, FxHashSet};
+
+/// Struct for replacing names with valid C identifiers for --gen-c-runnable.
+pub struct NameTransformer {
+    new_symbol_table: SymbolTable,
+    mapped_names: FxHashMap<String, String>,
+    used_names: FxHashSet<String>,
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs:14]: Comment explaining these

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs [hunk 13]
```diff
@@ -0,0 +1,245 @@
...
+            used_names: FxHashSet::default(),
+        }
+        .transform_symbol_table(original_symbol_table)
+    }
+
+    /// Converts an arbitrary identifier into a valid C identifier.
+    fn normalize_identifier(&mut self, orig_name: &str) -> String {
+        assert!(!orig_name.is_empty(), "Received empty identifier.");
+
+        // If name already encountered, return same result
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs:33]: Comment explaining that this isn't just an optimization, its required for correctness

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs [hunk 14]
```diff
@@ -0,0 +1,245 @@
...
+                        name
+                    } else {
+                        valid_chars
+                    }
+                }
+                None => "".to_string(),
+            };
+
+            // Replace reserved names with alternatives
+            let mut illegal_names = [("case", "case_"), ("default", "default_")];
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs:79]: I imagine this is not exhaustive?

Comment (danielsn) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs:79]: Really, we should just use the list of C reserved words

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/nondet_transformer.rs [hunk 15]
```diff
@@ -0,0 +1,122 @@
...
+    fn mut_symbol_table(&mut self) -> &mut SymbolTable {
+        &mut self.new_symbol_table
+    }
+
+    /// Get owned symbol table.
+    fn extract_symbol_table(self) -> SymbolTable {
+        self.new_symbol_table
+    }
+
+    /// Transform nondets to create default values for the expected type.
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/nondet_transformer.rs:46]: pseudocode

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/nondet_transformer.rs [hunk 16]
```diff
@@ -0,0 +1,122 @@
...
+        let identifier = format!("non_det_{}", type_to_string(&transformed_typ));
+        let function_type = Type::code(vec![], transformed_typ);
+
+        // Create non_det function which returns default value in postprocessing
+        self.nondet_types.insert(identifier.clone(), function_type.clone());
+
+        Expr::symbol_expression(identifier, function_type).call(vec![])
+    }
+
+    /// Don't transform padding fields so that they are ignored by CBMC --dump-c.
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/nondet_transformer.rs:59]: Give example of what happens if you do and don't do this

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/passes.rs [hunk 17]
```diff
@@ -2,12 +2,19 @@
...
 
 use super::super::SymbolTable;
+use super::gen_c_transformer::{ExprTransformer, NameTransformer, NondetTransformer};
 use super::identity_transformer::IdentityTransformer;
 
 /// Performs each pass provided on the given symbol table.
 pub fn do_passes(mut symtab: SymbolTable, pass_names: &[String]) -> SymbolTable {
     for pass_name in pass_names {
         symtab = match &pass_name[..] {
+            "gen-c" => {
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/passes.rs:12]: Does order matter here?

File: library/rmc/gen_c_lib.c [hunk 18]
```diff
@@ -0,0 +1,55 @@
+// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
+// SPDX-License-Identifier: Apache-2.0 OR MIT
+
```
Comment (danielsn) [inline library/rmc/gen_c_lib.c:3]: File level comment: these are stubs to link that make things executable

File: library/rmc/gen_c_lib.c [hunk 19]
```diff
@@ -0,0 +1,55 @@
...
+#include <assert.h>
+#include <limits.h>
+#include <math.h>
+#include <stdio.h>
+#include <stdbool.h>
+#include <string.h>
+
+// If a user assumes something, then it should hold
+void __CPROVER_assume(int condition) {
+    assert(condition);
```
Comment (danielsn) [inline library/rmc/gen_c_lib.c:13]: What to do here depends on what the user expects.

File: library/rmc/gen_c_lib.c [hunk 20]
```diff
@@ -0,0 +1,55 @@
...
+float powif(float base, int expt) {
+    return (float) powi((double) base, expt);
+}
+
+// Used by cbmc invariants
+typedef bool __CPROVER_bool;
+
+#define OBJECT_SIZE(value) sizeof(*value)
+
+// A temporary definition to always cause checks to be true.
```
Comment (danielsn) [inline library/rmc/gen_c_lib.c:37]: ????

File: library/rmc/gen_c_lib.c [hunk 21]
```diff
@@ -0,0 +1,55 @@
...
+#define POINTER_OBJECT(value) 0
+
+#define overflow(op, typ, var1, var2) \
```
Comment (danielsn) [inline library/rmc/gen_c_lib.c:40]: Use the gcc builtins!

Comment (danielsn) [reply library/rmc/gen_c_lib.c:40]: https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html

File: library/rmc/gen_c_lib.c [hunk 22]
```diff
@@ -0,0 +1,55 @@
...
+    (strcmp(op, "+") == 0) ? ( \
```
Comment (danielsn) [inline library/rmc/gen_c_lib.c:41]: instead of strcmp, you could `op[0] == '+'`

File: library/rmc/gen_c_lib.c [hunk 23]
```diff
@@ -0,0 +1,55 @@
...
+    ) : (strcmp(op, "-") == 0) ? ( \
+        ((var1 < 0) && (var2 > 0) && (var1 - var2 > 0)) || \
+        ((var1 > 0) && (var2 < 0) && (var1 - var2 < 0)) \
+    ) : (strcmp(op, "*") == 0) ? ( \
+        (var1 != 0) && ((var1 * var2) / var1 != var2) \
+    ) : ( \
+        1 \
+    )
+
+#define byte_extract_little_endian(from_val, offset, to_type) \
```
Comment (danielsn) [inline library/rmc/gen_c_lib.c:53]: Works on little endian machines only :)

File: scripts/rmc.py [hunk 24]
```diff
@@ -255,6 +258,83 @@ def run_goto_instrument(input_filename, output_filename, args, verbose=False, dr
...
     return run_goto_instrument(goto_filename, c_filename, ["--dump-c"], verbose, dry_run=dry_run)
+    
+# Fix remaining issues with output of --gen-c-runnable
+def gen_c_postprocess(c_filename, dry_run=False):
+    if not dry_run:
+        with open(c_filename, "r") as f:
+            lines = f.read().splitlines()
+
+        # Remove header line
+        lines.pop(0)
```
Comment (danielsn) [inline scripts/rmc.py:269]: If you run it like this
```
goto-instrument --dump-c be.goto be.c
```

instead of like that 
```
goto-instrument --dump-c be.goto > be.c
```

You don't have the line you need to pop

**Review by danielsn — CHANGES_REQUESTED** [review]

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symbol_table.rs [hunk 25]
```diff
@@ -68,6 +68,11 @@ impl SymbolTable {
     pub fn update_fn_declaration_with_definition(&mut self, name: &str, body: Stmt) {
         self.symbol_table.get_mut(name).unwrap().update_fn_declaration_with_definition(body);
     }
+
+    /// Removes a symbol from the symbol table
+    pub fn remove(&mut self, name: &str) -> Option<Symbol> {
```
[the remark this answers is not in the document]
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symbol_table.rs:73]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/common.rs [hunk 26]
```diff
@@ -0,0 +1,51 @@
+use super::super::super::Type;
+
+/// Create a string representation of type for use as variable name suffix.
+pub fn type_to_string(typ: &Type) -> String {
```
[the remark this answers is not in the document]
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/common.rs:4]: Moved to `typ.rs`.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/common.rs [hunk 27]
```diff
@@ -0,0 +1,51 @@
+use super::super::super::Type;
+
+/// Create a string representation of type for use as variable name suffix.
```
[the remark this answers is not in the document]
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/common.rs:3]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 2 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:19]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 3 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:16]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 4 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:33]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 5 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:42]: Changed.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 6 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:53]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 7 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:65]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 8 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:70]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 9 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:116]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 10 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:156]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 11 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:230]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs (hunk 13 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs:33]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs (hunk 12 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs:14]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs (hunk 14 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs:79]: Created issue.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/nondet_transformer.rs (hunk 15 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/nondet_transformer.rs:46]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/nondet_transformer.rs (hunk 16 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/nondet_transformer.rs:59]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/passes.rs (hunk 17 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/passes.rs:12]: Done.

File: library/rmc/gen_c_lib.c (hunk 18 above)
Comment (vecchiot-aws) [reply library/rmc/gen_c_lib.c:3]: Done.

File: library/rmc/gen_c_lib.c (hunk 23 above)
Comment (vecchiot-aws) [reply library/rmc/gen_c_lib.c:53]: Added comment.

File: library/rmc/gen_c_lib.c (hunk 20 above)
Comment (vecchiot-aws) [reply library/rmc/gen_c_lib.c:37]: Added more detail.

File: library/rmc/gen_c_lib.c (hunk 19 above)
Comment (vecchiot-aws) [reply library/rmc/gen_c_lib.c:13]: Removed assert and added comment.

File: library/rmc/gen_c_lib.c (hunk 22 above)
Comment (vecchiot-aws) [reply library/rmc/gen_c_lib.c:41]: Done.

File: library/rmc/gen_c_lib.c (hunk 21 above)
Comment (vecchiot-aws) [reply library/rmc/gen_c_lib.c:40]: This isn't supported in my gcc; will have to check how to do tomorrow.

File: scripts/rmc.py (hunk 24 above)
Comment (vecchiot-aws) [reply scripts/rmc.py:269]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/common.rs (hunk 1 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/common.rs]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs [hunk 28]
```diff
@@ -0,0 +1,254 @@
...
+    fn normalize_identifier(&mut self, orig_name: &str) -> String {
+        assert!(!orig_name.is_empty(), "Received empty identifier.");
+
+        // If name already encountered, return same result;
+        // this is necessary for correctness to avoid a single name
+        // being mapped to two different names later on
+        match self.mapped_names.get(orig_name) {
+            Some(result) => return result.clone(),
+            None => (),
+        }
```
Comment (danielsn) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs:44]: `if let Some(result) = self.mapped_names.get(orig_name) { return result.clone() }`

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 29]
```diff
@@ -0,0 +1,268 @@
...
+        _typ: &Type,
+        op: &BinaryOperand,
+        lhs: &Expr,
+        rhs: &Expr,
+    ) -> Expr {
+        let lhs = self.transform_expr(lhs);
+        let rhs = self.transform_expr(rhs);
+
+        match op {
+            BinaryOperand::Implies => lhs.not().bitor(rhs).not().not(),
```
Comment (vecchiot-aws) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:136]: Cast to bool

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs [hunk 30]
```diff
@@ -0,0 +1,268 @@
...
+
+    /// Prevent error for too large constants with u128.
+    fn transform_expr_int_constant(&mut self, typ: &Type, value: &BigInt) -> Expr {
+        let transformed_typ = self.transform_type(typ);
+        bignum_to_expr(value, &transformed_typ)
+    }
+
+    /// When indexing into a SIMD vector, cast to a pointer first to make legal indexing in C.
+    /// `typ __attribute__((vector_size (size * sizeof(typ)))) var;`
+    /// `((typ*) &var)[index]`
```
Comment (vecchiot-aws) [inline compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:149]: Add an issue + comment

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs (hunk 28 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/name_transformer.rs:44]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 29 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:136]: Done.

File: compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs (hunk 30 above)
Comment (vecchiot-aws) [reply compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symtab_transformer/gen_c_transformer/expr_transformer.rs:149]: Done.

File: library/rmc/gen_c_lib.c (hunk 21 above)
Comment (vecchiot-aws) [reply library/rmc/gen_c_lib.c]: Done.

**Review by danielsn — APPROVED** [review]
